import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import graph from "../lib/graph";
import { useEffect } from "react";
export default function Home() {
  useEffect(() => {
    graph();
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ height: "870px", width: "1403px", position: "relative" }}>
          <canvas id="map" style={{ position: "relative" }}></canvas>
          <h1
            id="path"
            style={{
              position: "absolute",
              top: "50%",
              left: "10px",
              color: "white",
            }}
          >
            awdaw
          </h1>
        </div>
        <button id="copy">Click to copy initialization list!</button>
        <p>Draw Speed</p>
        <input id="drawSpeed" type="range" min="0" max="100"></input>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by: Konstantin Victoria<br></br>You can decrease the draw time
          by adjusting the slider. You do not need to wait for it to finish
          drawing in order to copy the initializion list.
        </a>
      </footer>
    </div>
  );
}
